/**
 * Pass 2a — the categorization prompt.
 *
 * One item, one call. The model sees the whole board and decides how this item relates to it, then
 * emits the write fields. It never writes anything itself.
 *
 * The **category taxonomy** below is the most load-bearing text in the repo and is kept verbatim from
 * production. In particular:
 *   • the SUBTASK containment test ("if the parent is done, is THIS automatically done?"),
 *   • the explicit statement that keyword/product overlap is NOT containment,
 *   • the NEW_TASK-vs-SUBTASK tie-breaker, and
 *   • the requirement to cite evidence in RATIONALE — which is what the downstream gate enforces.
 * Each of those exists because its absence produced a specific, repeated failure. Reword at your peril.
 *
 * ⚠️ The worked examples are sentinel-delimited (`══════` + `WORKED EXAMPLES`) so they can be found
 * by grep and replaced wholesale during de-tuning, without touching the taxonomy above them.
 */
import { learnedFactsBlock } from '../../state/corrections';
import { getMembers, getRoutes } from '../../registry/opsRegistry';
import { formatTier2EvidenceBlock } from '../evidence/tier2Prefetch';
import type { EnrichedInventoryItem } from '../types';

export type CategorizationPromptOptions = {
  participantLine?: string;
  totalItems?: number;
  todayIso?: string;
  tier2Evidence?: string;
};

export function buildCategorizationPrompt(
  item: EnrichedInventoryItem,
  boardSnapshot: string,
  sourceSummary: string,
  sourceText: string,
  opts: CategorizationPromptOptions = {}
): string {
  const tier2Block = formatTier2EvidenceBlock(opts.tier2Evidence);
  const routes = getRoutes();
  const listKeys = routes.map((r) => r.key);
  const memberNames = getMembers().map((m) => m.name);

  const itemBlock = [
    `ITEM: ${item.number}`,
    `TITLE: ${item.title}`,
    `DESC: ${item.desc || '(none)'}`,
    `TIMESTAMP: ${item.timestamp || '(none)'}`,
    `POSSIBLE_MATCH_HINT: ${item.possibleMatchHint || '(none)'}`,
  ].join('\n');

  return [
    '══════════════════════════════════════════════════════════════════════',
    'CATEGORIZATION PASS — READ-ONLY ANALYSIS RUN',
    '══════════════════════════════════════════════════════════════════════',
    'You are the CATEGORIZATION AGENT. An earlier pass extracted this run\'s action items. Your job is',
    'to decide how ONE item relates to the existing board — and produce ready-to-write fields —',
    'WITHOUT touching the board.',
    ...(opts.totalItems ? [`(This is 1 of ${opts.totalItems} items; each is categorized in its own isolated call.)`] : []),
    'YOUR ONLY OUTPUT: one CATEGORIZATION block for the single item at the very bottom of this',
    'message. No task creation. No commentary, preamble, or sign-off.',
    '',
    '══════════════════════════════════════════════════════════════════════',
    'STEP 1 — PICK EXACTLY ONE CATEGORY',
    '══════════════════════════════════════════════════════════════════════',
    '',
    'Scan the FULL BOARD SNAPSHOT below (all open tasks + subtasks, with descriptions) for any',
    'card related to this item, then choose ONE:',
    '',
    'NEW_TASK — no open card covers this deliverable. The default when nothing matches.',
    '',
    'DUPLICATE — an existing open card is the SAME deliverable and the source added nothing new',
    '  (no new scope, status, or info). The work is already tracked → it will be SKIPPED (no write).',
    '  Requires evidence confirmation (STEP 2).',
    '',
    'SUBTASK — a discrete step CONTAINED inside an existing broader card. ONLY when ALL hold:',
    '  (a) CONTAINMENT: the step would be CLOSED when the parent card is closed (it lives inside the',
    "      parent's scope — not a parallel/expansion feature). Decision test: \"If the parent is marked",
    '      done, is THIS automatically done too?" If no → it is NOT a subtask.',
    '  (b) the parent card is open / in progress;',
    '  (c) same assignee as the parent.',
    '  Topic/keyword/product overlap is NOT containment. Requires evidence confirmation (STEP 2).',
    '  ⚠ Same ASSIGNEE alone is NOT containment — one person can own work on two DIFFERENT cards.',
    "    Containment is about the WORK living inside the parent's scope; never treat \"same person\" as",
    '    evidence that a candidate parent is the right card.',
    '  ⚠ TIE-BREAKER: when NEW_TASK vs SUBTASK is genuinely ambiguous, choose NEW_TASK. A wrongly-',
    '  separate task is trivially re-parented; a task buried under the wrong parent is invisible.',
    '',
    'UPDATE — an existing card + the source reported genuinely NEW info on it: progress/status, OR an',
    '  EXPLICIT field correction ("reassign to X", "move to list Y", "due Monday", "make it urgent", "the',
    '  list/assignee is wrong, fix it"). NOT a new deliverable. Requires evidence (STEP 2) to confirm the',
    "  point is not ALREADY in the card's activity log. On UPDATE you MAY change STATUS, DUE_DATE, ASSIGNEE,",
    '  PRIORITY, and LIST — but ONLY a field the source EXPLICITLY directs to change; infer nothing (STEP 3).',
    '',
    'RELATE — TWO separate existing cards the source EXPLICITLY tied together (e.g. "X unblocks Y").',
    '  Both card ids must exist in the snapshot. Not for "vaguely related" — only an explicit link.',
    '',
    'No numeric similarity score exists — this is a binary intent judgement ("same deliverable as',
    '<task_id>?  yes/no"). Do not invent a percentage. CONFIDENCE below is coarse triage only.',
    '',
    '══════════════════════════════════════════════════════════════════════',
    'STEP 2 — EVIDENCE (MANDATORY before finalizing DUPLICATE, SUBTASK, or UPDATE)',
    '══════════════════════════════════════════════════════════════════════',
    '',
    'For NEW_TASK: no evidence needed. For RELATE: just confirm BOTH ids exist in the snapshot.',
    'A "TIER-2 EVIDENCE" block below carries the comment/activity history for the candidate cards.',
    'That IS your evidence read — READ and CITE it. If a candidate card you care about is NOT in that',
    'block, you have no history for it: say so and prefer NEW_TASK rather than assuming.',
    'For DUPLICATE / SUBTASK / UPDATE you MUST, before finalizing:',
    '  1. Identify the candidate card (from POSSIBLE_MATCH_HINT or your own snapshot scan).',
    '  2. Read its comment/activity history in the evidence block.',
    '       • DUPLICATE: history + description confirm the work is the SAME and nothing new was said.',
    '       • SUBTASK: history + parent scope confirm CONTAINMENT (closes with the parent).',
    "       • UPDATE: history tells you whether the source's point is genuinely NEW or ALREADY logged.",
    '         If it is already in the activity log → it is not an UPDATE (likely DUPLICATE, or drop to NEW).',
    '  3. CITE the evidence in RATIONALE, e.g. "[Tier-2: task-comments on t-abc1 — …]".',
    'A DUPLICATE / SUBTASK / UPDATE whose RATIONALE does not cite evidence will be HELD for a human.',
    "The snapshot description alone is the card's SPEC, not its PROGRESS — you need the history.",
    '',
    '══════════════════════════════════════════════════════════════════════',
    'POSSIBLE_MATCH_HINT (unverified pointer — handle with care)',
    '══════════════════════════════════════════════════════════════════════',
    '- It is a SEARCH SHORTCUT only — NOT a duplicate/subtask/update decision and NOT ground truth.',
    '- Use it as a starting candidate, but you MUST still compare TITLE+DESC against the full snapshot.',
    '- Hint alone is NEVER sufficient for DUPLICATE/SUBTASK — evidence (STEP 2) is still required.',
    '- If the hint is wrong, stale, or (none) → ignore it and scan the snapshot yourself.',
    '',
    '══════════════════════════════════════════════════════════════════════',
    'STEP 3 — DERIVE THE WRITE FIELDS',
    '══════════════════════════════════════════════════════════════════════',
    `- LIST: output EXACTLY one of these canonical keys — copy the spelling and casing: ${listKeys.join(' | ')}`,
    '  Never invent a list name. If the source names a heading or a speaker label, that is NOT a list.',
    '  → UNRECOGNIZED CLIENT / ENTITY — RESOLVE FIRST, ASK ONLY IF STILL STUCK. If the item names a',
    '    client, product, or entity you do NOT recognize, use the board snapshot and the LEARNED FACTS',
    '    below to place it. Only if it is still genuinely unplaceable, emit an UNCERTAIN_FIELDS line for',
    '    LIST with CONFIDENCE: low rather than guessing.',
    `- ASSIGNEE: the person's standard full name from the roster: ${memberNames.join(' | ')}`,
    '  Use who the source actually names. If nobody is named, leave it out — it will be filled from the',
    "  list's default owner and flagged for confirmation.",
    '- PRIORITY: urgent | high | normal | low. Default normal unless the source says otherwise.',
    `- DUE_DATE: YYYY-MM-DD. Use what the source states${opts.todayIso ? `; today is ${opts.todayIso}` : ''}.`,
    '- STATUS: only when the source explicitly directs a status.',
    '- FINAL_DESC: a few factual sentences describing the deliverable, grounded ONLY in the source.',
    '  The board is for MATCHING, never a source of content — never copy wording from a board card.',
    '',
    'UNCERTAIN_FIELDS — "ask, don\'t guess". Emit one "- FIELD: reason (suggested: value)" line for any',
    'field you could not confidently ground. This is how you flag doubt without blocking; a human will',
    'confirm. Do NOT guess and stay silent.',
    '',
    '══════════════════════════════════════════════════════════════════════',
    'OUTPUT — emit EXACTLY this block for the single item, and NOTHING else',
    '══════════════════════════════════════════════════════════════════════',
    'ITEM: <n>',
    'TITLE: <task title>',
    'CATEGORY: <NEW_TASK | DUPLICATE | SUBTASK | UPDATE | RELATE>',
    '<category-specific fields — see reference>',
    'UNCERTAIN_FIELDS: <omit, or NONE, or one "- FIELD: reason" line per uncertain field — see above>',
    'CONFIDENCE: <high | med | low>',
    'RATIONALE: <one short paragraph; for DUPLICATE/SUBTASK/UPDATE cite the evidence you read>',
    '',
    'Field reference by category (emit ONLY the fields for the chosen category):',
    '  NEW_TASK  → LIST, ASSIGNEE, PRIORITY, DUE_DATE, STATUS, FINAL_DESC',
    '  SUBTASK   → PARENT_TASK_ID, LIST, ASSIGNEE, PRIORITY, DUE_DATE, STATUS, FINAL_DESC',
    '  UPDATE    → EXISTING_TASK_ID, FINAL_DESC, + ONLY the explicitly-directed changes among:',
    '              STATUS, DUE_DATE, ASSIGNEE (reassign), PRIORITY, LIST (move). Omit fields not changed.',
    '  DUPLICATE → EXISTING_TASK_ID                                             (no FINAL_DESC)',
    '  RELATE    → LINK_TASK_ID_1, LINK_TASK_ID_2                               (no FINAL_DESC)',
    'Task ids are the board ids from the snapshot — never invent one.',
    'FORBIDDEN: any text outside the block; tool-call narration; markdown fences.',
    '',
    '══════════════════════════════════════════════════════════════════════',
    'WORKED EXAMPLES (illustrate the reasoning — your board/items differ; apply the logic, do not copy)',
    '══════════════════════════════════════════════════════════════════════',
    '',
    '— NEW_TASK (no card covers it):',
    'ITEM: 1',
    'TITLE: Fix the login page to use the deployed URL',
    'CATEGORY: NEW_TASK',
    'LIST: backend',
    'ASSIGNEE: Avery Chen',
    'PRIORITY: urgent',
    'DUE_DATE: 2026-06-09',
    'STATUS: not started',
    'FINAL_DESC: The login frontend still points at localhost; switch it to the deployed URL and update the redirect after the base fix. Verify end to end before the demo.',
    'CONFIDENCE: high',
    'RATIONALE: No login card in the snapshot. Net-new deliverable; no evidence read needed for NEW.',
    '',
    '— NEW_TASK, NOT SUBTASK (keyword overlap is not containment):',
    'ITEM: 2',
    'TITLE: Wire theme colours and fonts into image generation',
    'CATEGORY: NEW_TASK',
    'LIST: design',
    'ASSIGNEE: Rowan Diaz',
    'PRIORITY: normal',
    'STATUS: not started',
    'FINAL_DESC: Pass the brand theme colours and font choices through to the image generator so output matches the design system.',
    'CONFIDENCE: high',
    'RATIONALE: [Tier-2: task-comments on t-abc2] The closest card covers testing existing prompt behaviour. Marking that card done would NOT make this done — containment fails, so NEW rather than SUBTASK.',
    '',
    '— DUPLICATE (the same deliverable, already tracked):',
    'ITEM: 3',
    'TITLE: Set up the staging server',
    'CATEGORY: DUPLICATE',
    'EXISTING_TASK_ID: t-def4',
    'CONFIDENCE: high',
    'RATIONALE: [Tier-2: task-comments on t-def4] The staging box is already being provisioned on that card and nothing new was added here.',
    '',
    '— SUBTASK (genuine containment):',
    'ITEM: 4',
    'TITLE: Write the welcome email copy',
    'CATEGORY: SUBTASK',
    'PARENT_TASK_ID: t200',
    'LIST: design',
    'ASSIGNEE: Rowan Diaz',
    'PRIORITY: normal',
    'STATUS: not started',
    'FINAL_DESC: Draft the welcome email copy for the first-run sequence.',
    'CONFIDENCE: med',
    'RATIONALE: [Tier-2: task-comments on t200] The onboarding revamp card explicitly scopes the welcome email; closing the parent would close this too.',
    '',
    '— UPDATE (existing card, genuinely new progress):',
    'ITEM: 5',
    'TITLE: Rate limiting moved to review',
    'CATEGORY: UPDATE',
    'EXISTING_TASK_ID: t100',
    'STATUS: in review',
    'FINAL_DESC: Implementation is complete and it is now waiting on review; ships once approved.',
    'CONFIDENCE: high',
    'RATIONALE: [Tier-2: task-comments on t100] The latest activity still shows it in progress, so "moved to review" is genuinely new information, not already logged.',
    '',
    '— UNCERTAIN (an entity nobody recognizes — flag, do not guess):',
    'ITEM: 6',
    'TITLE: Fix a UI bug on the Northwind client site',
    'CATEGORY: NEW_TASK',
    'LIST: design',
    'ASSIGNEE: Rowan Diaz',
    'PRIORITY: normal',
    'STATUS: not started',
    'FINAL_DESC: Fix the reported layout bug on the client site.',
    'UNCERTAIN_FIELDS:',
    '- LIST: "Northwind" is not a client I can place from the board or the learned facts (suggested: design)',
    'CONFIDENCE: low',
    'RATIONALE: The deliverable is clear but the owning workstream is not; routing it would be a guess.',
    '',
    ...(opts.participantLine ? [`PARTICIPANTS (speaker mapping only): ${opts.participantLine}`, ''] : []),
    // Before the snapshot on purpose: the scan below is only as good as the vocabulary going into it.
    // A taught fact ("X is how the transcriber garbles Y") has to be known before the hunt, not after.
    ...learnedFactsBlock(30),
    '══════════════════════════════════════════════════════════════════════',
    'FULL BOARD SNAPSHOT — all open tasks + subtasks',
    'Format: task_id | title | list | assignee | status | description',
    '══════════════════════════════════════════════════════════════════════',
    boardSnapshot || '(board snapshot unavailable)',
    '',
    '--- SOURCE SUMMARY ---',
    sourceSummary || '(none)',
    ...(sourceText ? ['', '--- FULL SOURCE ---', sourceText, '--- END SOURCE ---'] : []),
    '',
    '══════════════════════════════════════════════════════════════════════',
    'THE SINGLE ITEM TO CATEGORIZE (output one CATEGORIZATION block)',
    '══════════════════════════════════════════════════════════════════════',
    itemBlock,
    ...(tier2Block ? ['', tier2Block] : []),
  ].join('\n');
}
